name: Checks
on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    name: 'Build & Release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run test



